"""initial migration

Revision ID: 083c114aab2c
Revises: 
Create Date: 2025-06-08 20:40:31.500471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '083c114aab2c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ihr_asn',
    sa.Column('number', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tartiflette', sa.Boolean(), nullable=False),
    sa.Column('disco', sa.Boolean(), nullable=False),
    sa.Column('ashash', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('number')
    )
    op.create_table('ihr_country',
    sa.Column('code', sa.String(length=4), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tartiflette', sa.Boolean(), nullable=False),
    sa.Column('disco', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('ihr_hegemonycone',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('timebin', sa.DateTime(), nullable=False),
    sa.Column('conesize', sa.Integer(), nullable=False),
    sa.Column('af', sa.Integer(), nullable=False),
    sa.Column('asn_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['asn_id'], ['ihr_asn.number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'timebin')
    )
    op.execute("SELECT create_hypertable('ihr_hegemonycone', by_range('timebin', INTERVAL '2 day'));")
    op.execute("ALTER TABLE ihr_hegemonycone SET (timescaledb.compress, timescaledb.compress_segmentby = 'asn_id,af', timescaledb.compress_orderby = 'timebin');")
    op.execute("SELECT add_compression_policy('ihr_hegemonycone', INTERVAL '7 days');")
    op.execute('CREATE INDEX IF NOT EXISTS ihr_hegemonycone_asn_id_timebin_idx ON ihr_hegemonycone (asn_id, timebin DESC);')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE ihr_hegemonycone SET (timescaledb.compress = false);')
    op.execute("SELECT remove_compression_policy('ihr_hegemonycone', if_exists => TRUE);")
    op.execute('DROP INDEX IF EXISTS ihr_hegemonycone_asn_id_timebin_idx;')
    op.drop_table('ihr_hegemonycone')
    op.drop_table('ihr_country')
    op.drop_table('ihr_asn')
    # ### end Alembic commands ###
