"""Initial migration

Revision ID: 569035a81799
Revises: 
Create Date: 2025-06-05 11:10:26.127839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '569035a81799'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ihr_country', sa.Column('continent', sa.String(length=50), nullable=True))
    op.add_column('ihr_country', sa.Column('language', sa.String(length=50), server_default=sa.text("'EN'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ihr_country', 'language')
    op.drop_column('ihr_country', 'continent')
    # ### end Alembic commands ###
