"""Changed defult language to AR in Country

Revision ID: 59fba5ae8f0b
Revises: 569035a81799
Create Date: 2025-06-05 11:14:35.640233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59fba5ae8f0b'
down_revision: Union[str, None] = '569035a81799'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ihr_country', 'language',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'AR'"),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ihr_country', 'language',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'EN'::character varying"),
               existing_nullable=False)
    # ### end Alembic commands ###
