"""initial migration3

Revision ID: 650fd402b9d5
Revises: 8865d4f4ee7f
Create Date: 2025-06-08 21:57:18.231591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '650fd402b9d5'
down_revision: Union[str, None] = '8865d4f4ee7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ihr_country', sa.Column('continent', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ihr_country', 'continent')
    # ### end Alembic commands ###
