"""initial migration2

Revision ID: 8865d4f4ee7f
Revises: bbb6ce9ca16b
Create Date: 2025-06-08 21:56:37.124252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8865d4f4ee7f'
down_revision: Union[str, None] = 'bbb6ce9ca16b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE INDEX IF NOT EXISTS ihr_hegemonycone_asn_id_idx ON ihr_hegemonycone (asn_id);')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP INDEX IF EXISTS ihr_hegemonycone_asn_id_idx;')
    # ### end Alembic commands ###
