"""Removed columns from country

Revision ID: bd82e57154c5
Revises: 59fba5ae8f0b
Create Date: 2025-06-05 11:17:52.058567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd82e57154c5'
down_revision: Union[str, None] = '59fba5ae8f0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ihr_country', 'language')
    op.drop_column('ihr_country', 'continent')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ihr_country', sa.Column('continent', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('ihr_country', sa.Column('language', sa.VARCHAR(length=50), server_default=sa.text("'AR'::character varying"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
